version: "3"

services:
  api:
    container_name: authentication
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - REDIS_URI=redis://redis:6379
  #   depends_on:
  #     - redis
  # redis:
  #   container_name: authentication_redis
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
