version: "3"

services:
  api:
    container_name: authentication
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - ACCESS_TOKEN_PRIVATE_KEY=
      - ACCESS_TOKEN_PUBLIC_KEY=
